import { Ionicons } from '@expo/vector-icons';

// Enum for expense categories (keys only)
export enum ExpenseCategory {
  FOOD_AND_DRINKS = 'FOOD_AND_DRINKS',
  TRANSPORT_AND_VEHICLES = 'TRANSPORT_AND_VEHICLES',
  HOUSING_AND_SERVICES = 'HOUSING_AND_SERVICES',
  HEALTH_AND_WELLNESS = 'HEALTH_AND_WELLNESS',
  EDUCATION_AND_CULTURE = 'EDUCATION_AND_CULTURE',
  ONLINE_SHOPPING = 'ONLINE_SHOPPING',
  FINANCES = 'FINANCES',
  FAMILY_AND_CARE = 'FAMILY_AND_CARE',
  LEISURE_AND_ENTERTAINMENT = 'LEISURE_AND_ENTERTAINMENT',
  TAXES_AND_DUTIES = 'TAXES_AND_DUTIES',
  SAVINGS_AND_INVESTMENT = 'SAVINGS_AND_INVESTMENT',
  CLOTHING_AND_ACCESSORIES = 'CLOTHING_AND_ACCESSORIES',
  GIFTS_AND_DONATIONS = 'GIFTS_AND_DONATIONS',
  MAINTENANCE_AND_CARE = 'MAINTENANCE_AND_CARE',
  TRAVEL_AND_VACATIONS = 'TRAVEL_AND_VACATIONS',
  SUBSCRIPTIONS_AND_SERVICES = 'SUBSCRIPTIONS_AND_SERVICES',
  PERSONAL_CARE_AND_SPORTS = 'PERSONAL_CARE_AND_SPORTS',
  PETS_AND_ANIMALS = 'PETS_AND_ANIMALS',
  ART_AND_CULTURE = 'ART_AND_CULTURE',
  CHARITY_AND_VOLUNTEERING = 'CHARITY_AND_VOLUNTEERING',
  COMMUNICATIONS = 'COMMUNICATIONS',
  FINANCIAL_EDUCATION = 'FINANCIAL_EDUCATION',
  ALTERNATIVE_INVESTMENTS = 'ALTERNATIVE_INVESTMENTS',
  EMERGENCY_FUND = 'EMERGENCY_FUND',
}

export const ExpenseCategoryInfo = {
  [ExpenseCategory.FOOD_AND_DRINKS]: { name: 'Food and Drinks', icon: 'restaurant' },
  [ExpenseCategory.TRANSPORT_AND_VEHICLES]: { name: 'Transport and Vehicles', icon: 'car' },
  [ExpenseCategory.HOUSING_AND_SERVICES]: { name: 'Housing and Services', icon: 'home' },
  [ExpenseCategory.HEALTH_AND_WELLNESS]: { name: 'Health and Wellness', icon: 'medkit' },
  [ExpenseCategory.EDUCATION_AND_CULTURE]: { name: 'Education and Culture', icon: 'school' },
  [ExpenseCategory.ONLINE_SHOPPING]: { name: 'Online Shopping', icon: 'cart' },
  [ExpenseCategory.FINANCES]: { name: 'Finances', icon: 'wallet' },
  [ExpenseCategory.FAMILY_AND_CARE]: { name: 'Family and Care', icon: 'person' },
  [ExpenseCategory.LEISURE_AND_ENTERTAINMENT]: { name: 'Leisure and Entertainment', icon: 'film' },
  [ExpenseCategory.TAXES_AND_DUTIES]: { name: 'Taxes and Duties', icon: 'cash' },
  [ExpenseCategory.SAVINGS_AND_INVESTMENT]: { name: 'Savings and Investment', icon: 'bar-chart' },
  [ExpenseCategory.CLOTHING_AND_ACCESSORIES]: { name: 'Clothing and Accessories', icon: 'shirt' },
  [ExpenseCategory.GIFTS_AND_DONATIONS]: { name: 'Gifts and Donations', icon: 'gift' },
  [ExpenseCategory.MAINTENANCE_AND_CARE]: { name: 'Maintenance and Care', icon: 'hammer' },
  [ExpenseCategory.TRAVEL_AND_VACATIONS]: { name: 'Travel and Vacations', icon: 'airplane' },
  [ExpenseCategory.SUBSCRIPTIONS_AND_SERVICES]: { name: 'Subscriptions', icon: 'film' },
  [ExpenseCategory.PERSONAL_CARE_AND_SPORTS]: { name: 'Personal Care and Sports', icon: 'fitness' },
  [ExpenseCategory.PETS_AND_ANIMALS]: { name: 'Pets and Animals', icon: 'paw' },
  [ExpenseCategory.ART_AND_CULTURE]: { name: 'Art and Culture', icon: 'brush' },
  [ExpenseCategory.CHARITY_AND_VOLUNTEERING]: { name: 'Charity and Volunteering', icon: 'heart' },
  [ExpenseCategory.COMMUNICATIONS]: { name: 'Communications', icon: 'chatbubbles' },
  [ExpenseCategory.FINANCIAL_EDUCATION]: { name: 'Financial Education', icon: 'book' },
  [ExpenseCategory.ALTERNATIVE_INVESTMENTS]: { name: 'Alternative Investments', icon: 'globe' },
  [ExpenseCategory.EMERGENCY_FUND]: { name: 'Emergency Fund', icon: 'shield' },
}