import { Ionicons } from '@expo/vector-icons';

// Enum de categorías de gasto (solo claves)
export enum ExpenseCategory {
  ALIMENTACION_Y_BEBIDAS = 'ALIMENTACION_Y_BEBIDAS',
  TRANSPORTE_Y_VEHICULOS = 'TRANSPORTE_Y_VEHICULOS',
  VIVIENDA_Y_SERVICIOS = 'VIVIENDA_Y_SERVICIOS',
  SALUD_Y_BIENESTAR = 'SALUD_Y_BIENESTAR',
  EDUCACION_Y_CULTURA = 'EDUCACION_Y_CULTURA',
  COMPRAS_EN_LINEA = 'COMPRAS_EN_LINEA',
  FINANZAS = 'FINANZAS',
  FAMILIA_Y_CUIDADO = 'FAMILIA_Y_CUIDADO',
  OCIO_Y_ENTRETENIMIENTO = 'OCIO_Y_ENTRETENIMIENTO',
  IMPUESTOS_Y_TRIBUTOS = 'IMPUESTOS_Y_TRIBUTOS',
  AHORRO_E_INVERSION = 'AHORRO_E_INVERSION',
  ROPA_Y_ACCESORIOS = 'ROPA_Y_ACCESORIOS',
  REGALOS_Y_DONACIONES = 'REGALOS_Y_DONACIONES',
  MANTENIMIENTO_Y_CUIDADO = 'MANTENIMIENTO_Y_CUIDADO',
  VIAJES_Y_VACACIONES = 'VIAJES_Y_VACACIONES',
  SUSCRIPCIONES_Y_SERVICIOS = 'SUSCRIPCIONES_Y_SERVICIOS',
  CUIDADO_PERSONAL_Y_DEPORTES = 'CUIDADO_PERSONAL_Y_DEPORTES',
  MASCOTAS_Y_ANIMALES = 'MASCOTAS_Y_ANIMALES',
  ARTE_Y_CULTURA = 'ARTE_Y_CULTURA',
  CARIDAD_Y_VOLUNTARIADO = 'CARIDAD_Y_VOLUNTARIADO',
  COMUNICACIONES = 'COMUNICACIONES',
  EDUCACION_FINANCIERA = 'EDUCACION_FINANCIERA',
  INVERSIONES_ALTERNATIVAS = 'INVERSIONES_ALTERNATIVAS',
  FONDO_DE_EMERGENCIA = 'FONDO_DE_EMERGENCIA',
}

export const ExpenseCategoryInfo = {
  [ExpenseCategory.ALIMENTACION_Y_BEBIDAS]: { name: 'Alimentación y Bebidas', icon: 'restaurant' },
  [ExpenseCategory.TRANSPORTE_Y_VEHICULOS]: { name: 'Transporte y Vehículos', icon: 'car' },
  [ExpenseCategory.VIVIENDA_Y_SERVICIOS]: { name: 'Vivienda y Servicios', icon: 'home' },
  [ExpenseCategory.SALUD_Y_BIENESTAR]: { name: 'Salud y Bienestar', icon: 'medkit' },
  [ExpenseCategory.EDUCACION_Y_CULTURA]: { name: 'Educación y Cultura', icon: 'school' },
  [ExpenseCategory.COMPRAS_EN_LINEA]: { name: 'Compras en Línea', icon: 'cart' },
  [ExpenseCategory.FINANZAS]: { name: 'Finanzas', icon: 'wallet' },
  [ExpenseCategory.FAMILIA_Y_CUIDADO]: { name: 'Familia y Cuidado', icon: 'person' },
  [ExpenseCategory.OCIO_Y_ENTRETENIMIENTO]: { name: 'Ocio y Entretenimiento', icon: 'ios-film' },
  [ExpenseCategory.IMPUESTOS_Y_TRIBUTOS]: { name: 'Impuestos y Tributos', icon: 'cash' },
  [ExpenseCategory.AHORRO_E_INVERSION]: { name: 'Ahorro e Inversión', icon: 'bar-chart' },
  [ExpenseCategory.ROPA_Y_ACCESORIOS]: { name: 'Ropa y Accesorios', icon: 'shirt' },
  [ExpenseCategory.REGALOS_Y_DONACIONES]: { name: 'Regalos y Donaciones', icon: 'gift' },
  [ExpenseCategory.MANTENIMIENTO_Y_CUIDADO]: { name: 'Mantenimiento y Cuidado', icon: 'hammer' },
  [ExpenseCategory.VIAJES_Y_VACACIONES]: { name: 'Viajes y Vacaciones', icon: 'airplane' },
  [ExpenseCategory.SUSCRIPCIONES_Y_SERVICIOS]: { name: 'Suscripciones y Otros Servicios', icon: 'notifications' },
  [ExpenseCategory.CUIDADO_PERSONAL_Y_DEPORTES]: { name: 'Cuidado Personal y Deportes', icon: 'fitness' },
  [ExpenseCategory.MASCOTAS_Y_ANIMALES]: { name: 'Mascotas y Animales', icon: 'paw' },
  [ExpenseCategory.ARTE_Y_CULTURA]: { name: 'Arte y Cultura', icon: 'brush' },
  [ExpenseCategory.CARIDAD_Y_VOLUNTARIADO]: { name: 'Caridad y Voluntariado', icon: 'heart' },
  [ExpenseCategory.COMUNICACIONES]: { name: 'Comunicaciones', icon: 'chatbubbles' },
  [ExpenseCategory.EDUCACION_FINANCIERA]: { name: 'Educación Financiera', icon: 'book' },
  [ExpenseCategory.INVERSIONES_ALTERNATIVAS]: { name: 'Inversiones Alternativas', icon: 'globe' },
  [ExpenseCategory.FONDO_DE_EMERGENCIA]: { name: 'Fondo de Emergencia', icon: 'shield' },
}